info:
  description: ''
  title: ''
  version: ''
openapi: 3.0.0
paths:
  /opcapi/acampaigns_person_list/:
    get:
      operationId: acampaigns_person_list_list
      summary: Listar las campañas activas por usuario
      tags:
      - acampaigns_person_list
      responses:
        '200':
          description: Se retorna las listas correctamente
        '400':
          description: Hacen falta parametros en el query
  /opcapi/activecampaigns/:
    get:
      operationId: activecampaigns_list
      tags:
      - active campaigns
      responses:
        '200':
          description: Se retorna las listas correctamente
        '400':
          description: Hacen falta parametros en el query
  /opcapi/ages/:
    get:
      operationId: ages_list
      tags:
      - ages
  /opcapi/campaign/:
    post:
      operationId: campaign_create
      tags:
      - campaign
    put:
      operationId: campaign_update
      tags:
      - campaign
  /opcapi/campaigns_created_person/:
    get:
      operationId: campaigns_created_person_list
      tags:
      - campaigns_created_person
  /opcapi/campaigns_person/:
    get:
      operationId: campaigns_person_list
      tags:
      - campaigns_person
  /opcapi/change_zone/:
    put:
      operationId: change_zone_update
      tags:
      - change_zone
  /opcapi/cities/:
    get:
      operationId: cities_list
      tags:
      - cities
  /opcapi/city_person/:
    get:
      operationId: city_person_list
      tags:
      - city_person
  /opcapi/comunacorr/:
    post:
      operationId: comunacorr_create
      tags:
      - comunacorr
  /opcapi/corregimientos_comunas/:
    get:
      operationId: corregimientos_comunas_list
      tags:
      - corregimientos_comunas
  /opcapi/create_person/:
    post:
      operationId: create_person_create
      tags:
      - create_person
  /opcapi/docs/:
    get:
      operationId: docs_list
      tags:
      - docs
  /opcapi/educations/:
    get:
      operationId: educations_list
      tags:
      - educations
  /opcapi/gender/:
    get:
      operationId: gender_list
      tags:
      - gender
  /opcapi/gender_list/:
    get:
      operationId: gender_list_list
      tags:
      - gender_list
  /opcapi/keywords/:
    get:
      operationId: keywords_list
      tags:
      - keywords
  /opcapi/levelineducation/:
    get:
      operationId: levelineducation_list
      tags:
      - levelineducation
  /opcapi/levelseducation/:
    get:
      operationId: levelseducation_list
      tags:
      - levelseducation
  /opcapi/login/:
    post:
      description: 'Takes a set of user credentials and returns an access and refresh
        JSON web

        token pair to prove the authentication of those credentials.'
      operationId: login_create
      tags:
      - login
  /opcapi/narrative_user_campaign/:
    get:
      operationId: narrative_user_campaign_list
      tags:
      - narrative_user_campaign
  /opcapi/narratives/:
    get:
      operationId: narratives_list
      tags:
      - narratives
  /opcapi/notactivecampaigns/:
    get:
      operationId: notactivecampaigns_list
      tags:
      - notactivecampaigns
  /opcapi/obtain_campaign/:
    get:
      operationId: obtain_campaign_list
      tags:
      - obtain_campaign
  /opcapi/obtain_minmax_date/:
    get:
      operationId: obtain_minmax_date_list
      tags:
      - obtain_minmax_date
  /opcapi/obtain_opendata/:
    get:
      operationId: obtain_opendata_list
      tags:
      - obtain_opendata
  /opcapi/obtain_percentage/:
    get:
      operationId: obtain_percentage_list
      tags:
      - obtain_percentage
  /opcapi/obtain_person_campaign_logged/:
    get:
      operationId: obtain_person_campaign_logged_list
      tags:
      - obtain_person_campaign_logged
  /opcapi/obtain_topics_percentage/:
    get:
      operationId: obtain_topics_percentage_list
      tags:
      - obtain_topics_percentage
  /opcapi/person_data/:
    get:
      operationId: person_data_list
      tags:
      - person_data
    put:
      operationId: person_data_update
      tags:
      - person_data
  /opcapi/population_comunas/:
    get:
      operationId: population_comunas_list
      tags:
      - population_comunas
  /opcapi/predict/:
    get:
      operationId: predict_list
      tags:
      - predict
  /opcapi/refresh/:
    post:
      description: 'Takes a refresh type JSON web token and returns an access type
        JSON web

        token if the refresh token is valid.'
      operationId: refresh_create
      tags:
      - refresh
  /opcapi/register/:
    post:
      operationId: register_create
      tags:
      - register
  /opcapi/role_user/:
    get:
      operationId: role_user_list
      tags:
      - role_user
  /opcapi/roleu/{id}/:
    get:
      operationId: roleu_read
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - roleu
    post:
      operationId: roleu_create
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - roleu
    put:
      operationId: roleu_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: ''
          title: ''
          type: string
      tags:
      - roleu
  /opcapi/save_info_ruser/:
    post:
      operationId: save_info_ruser_create
      tags:
      - save_info_ruser
  /opcapi/save_info_zone/:
    post:
      operationId: save_info_zone_create
      tags:
      - save_info_zone
  /opcapi/saveall/:
    post:
      operationId: saveall_create
      tags:
      - saveall
  /opcapi/states/:
    get:
      operationId: states_list
      tags:
      - states
  /opcapi/topic_list/:
    get:
      operationId: topic_list_list
      tags:
      - topic_list
  /opcapi/topic_person_campaign/:
    get:
      operationId: topic_person_campaign_list
      tags:
      - topic_person_campaign
  /opcapi/veredas_neighborhoods/:
    get:
      operationId: veredas_neighborhoods_list
      tags:
      - veredas_neighborhoods
  /opcapi/zones/:
    get:
      operationId: zones_list
      tags:
      - zones
servers:
- url: ''
