# Generated by Django 2.2.4 on 2019-10-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='zoneType',
            field=models.CharField(choices=[('Urbana', 'Urbana'), ('Rural', 'Rural')], max_length=30),
        ),
    ]
