# Generated by Django 2.2.4 on 2019-10-14 02:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opcapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievedLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityNarrative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('endDate', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=30)),
                ('narrativesGoal', models.IntegerField()),
                ('accumulatedNarratives', models.IntegerField()),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ComunaCorregimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opcapp.City')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeGender', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pin', models.CharField(max_length=10)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opcapp.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='HigherLevelEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Tecnico/Tecnologo', 'Tecnico/Tecnologo'), ('Universitaria', 'Universitaria')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='NeightborhoodVereda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('comunaCorregimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opcapp.ComunaCorregimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('achievedLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opcapp.AchievedLevel')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opcapp.Gender')),
                ('higherLevelEducation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opcapp.HigherLevelEducation')),
                ('neightborhoodVeredaActual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personterritoryactual', to='opcapp.NeightborhoodVereda')),
                ('neightborhoodVeredaSource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personterritorysource', to='opcapp.NeightborhoodVereda')),
            ],
        ),
        migrations.CreateModel(
            name='RoleCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RoleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoneType', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('phoneNumber', models.CharField(max_length=30)),
                ('roleUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opcapp.RoleUser')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opcapp.Country')),
            ],
        ),
        migrations.CreateModel(
            name='PersonCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievedLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opcapp.AchievedLevel')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opcapp.Campaign')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opcapp.Gender')),
                ('higherLevelEducation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opcapp.HigherLevelEducation')),
                ('neightborhoodVeredaActual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personcampaignterritoryactual', to='opcapp.NeightborhoodVereda')),
                ('neightborhoodVeredaSource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personcampaignterritorysource', to='opcapp.NeightborhoodVereda')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opcapp.Person')),
                ('roleCampaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opcapp.RoleCampaign')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='opcapp.User'),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opcapp.Group')),
                ('personCampaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='opcapp.PersonCampaign')),
            ],
        ),
        migrations.AddField(
            model_name='neightborhoodvereda',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opcapp.Zone'),
        ),
        migrations.CreateModel(
            name='KeyConcept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('frequency', models.IntegerField()),
                ('activityNarrative', models.ManyToManyField(to='opcapp.ActivityNarrative')),
            ],
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('frequency', models.IntegerField()),
                ('activityNarrative', models.ManyToManyField(to='opcapp.ActivityNarrative')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opcapp.State'),
        ),
        migrations.AddField(
            model_name='activitynarrative',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opcapp.Campaign'),
        ),
        migrations.AddField(
            model_name='achievedlevel',
            name='higherLevelEducation',
            field=models.ManyToManyField(to='opcapp.HigherLevelEducation'),
        ),
    ]
