# Generated by Django 2.2.4 on 2019-11-08 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opcapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
    ]
