# Generated by Django 2.2.4 on 2019-10-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcapp', '0004_auto_20191026_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='startDate',
            field=models.DateField(),
        ),
    ]
