# Generated by Django 2.2.4 on 2019-11-01 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opcapp', '0005_auto_20191029_0010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NeightborhoodVereda',
            new_name='NeighborhoodVereda',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='neightborhoodVeredaActual',
            new_name='neighborhoodVeredaActual',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='neightborhoodVeredaSource',
            new_name='neighborhoodVeredaSource',
        ),
        migrations.RenameField(
            model_name='personcampaign',
            old_name='neightborhoodVeredaActual',
            new_name='neighborhoodVeredaActual',
        ),
        migrations.RenameField(
            model_name='personcampaign',
            old_name='neightborhoodVeredaSource',
            new_name='neighborhoodVeredaSource',
        ),
    ]
